# Generated by Django 4.0.5 on 2024-08-22 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hero', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hero',
            options={},
        ),
        migrations.AlterField(
            model_name='hero',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='hero',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='hero',
            name='subtitle',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='hero',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
