# Generated by Django 4.0.5 on 2024-08-23 11:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('experience', '0002_experience_delete_about'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experience',
            name='image',
        ),
        migrations.CreateModel(
            name='ExperienceImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='experience_images/')),
                ('experience', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='experience.experience')),
            ],
        ),
    ]
